service: aws-api-liner-notes-app-v2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: ${opt:stage, "dev"} # sls deploy --stage test (or staging, dev, prod)

functions:
  apicaller:
    handler: apicaller.handler
    events:
      - http:
          path: spotifygenius
          method: GET
          cors: true
